---
templateVersion: '2020-01-25'
componentName: aws.greengrass.mqtt.bridge
description: AWS Greengrass MQTT Bridge
publisher: AWS
version: '0.0.0'
componentType: plugin
manifests:
  - lifecycle:
    artifacts:
      - uri: s3://gg-dev-artifacts/$componentName/$version/aws.greengrass.mqtt.bridge.jar
