---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.mqtt.bridge
ComponentDescription: AWS Greengrass MQTT Bridge
ComponentPublisher: AWS
ComponentVersion: 0.0.0
ComponentType: aws.greengrass.plugin
Manifests:
  - Artifacts:
      - URI: s3://gg-dev-artifacts/$componentName/$version/aws.greengrass.mqtt.bridge.jar
    Dependencies:
      aws.greengrass.certificate.manager:
        VersionRequirement: '>=0.0.0'
        DependencyType: HARD
      #TODO: remove mqtt dependency
      aws.greengrass.mqtt:
        VersionRequirement: '>=0.0.0'
        DependencyType: HARD
