services:
    aws.greengrass.clientdevices.mqtt.Bridge:
        configuration:
            brokerUri: 'tcp://localhost:1883'
    main:
        dependencies:
            - aws.greengrass.clientdevices.mqtt.Bridge
