services:
    aws.greengrass.Nucleus:
        configuration:
            logging:
                level: "DEBUG"
    aws.greengrass.clientdevices.mqtt.Bridge:
        configuration:
            mqtt:
                version: "mqtt3"
            brokerUri: 'tcp://localhost:8883'
    main:
        dependencies:
            - aws.greengrass.clientdevices.mqtt.Bridge
